#!/usr/bin/perl -w
use strict;
print "usage:\ngeneabundance <clean_reads_list> <db_fasta_list> <gene_length>\n" and exit unless (@ARGV == 3);
my $fasta_list = $ARGV[1];
my $length_file = $ARGV[2];
my @database;
my %db;
open DB,"$fasta_list" or die $!;
while (<DB>){
	chomp;
	@_ = split /\t/;
	-e $_[1] or die "fasta file $_ doesn't exist!";
	$db{$_[1]} = $_[0];
	push @database,$_[1];
}
close DB;
my $main	= "./gene_abundance/alignment_parse.pl";
my $parse	= "./gene_abundance/gene_abundance_profiler.pl";
my $cwd = `pwd`;
chomp $cwd;
-e "alignment" or `mkdir alignment`;
-e "shell_alignment" or `mkdir shell_alignment`;
open CLEAN,"$ARGV[0]" or die;
open SHELL1,">shell_alignment/match.sh" or die $!;
open SHELL2,">shell_alignment/abun.sh" or die $!;
while (<CLEAN>){
	chomp;
	my ($name,$a,$b) = split /\s+/;
	-e $a and -e $b or die "clean data $a $b doesn't exist!";
	my $directory = "alignment/$name";
	if (! -d $directory) {`mkdir $directory`};
	open MATCH_LIST,">$directory/match.list" or die $!;
	foreach (@database){
		my $flag = "$cwd/$directory/$name-$db{$_}";
		print SHELL1 "soap -a $a -b $b -D $_.index -M 4 -o $flag.pm -2 $flag.sm -r 2 -p 10 -m 100 -x 1000\n";
		print MATCH_LIST "PE\t$flag.pm\nSE\t$flag.sm\n";
	}
	print SHELL2 "perl $main $cwd/$directory/match.list $cwd/$directory/$name.MATCH\n";
	print SHELL2 "perl $parse $length_file $cwd/$directory/$name.MATCH $cwd/$directory/$name.gene.abundance $cwd/$directory/$name.MATCH.log Dusko\n";
	close MATCH_LIST;
}
close CLEAN;
close SHELL1;
close SHELL2;
