/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A10/MetaVelvet_Ass_51 -ins_length 530 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A10/MetaVelvet_Ass_53 -ins_length 530 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A10/MetaVelvet_Ass_55 -ins_length 530 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A10/MetaVelvet_Ass_57 -ins_length 530 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A10/MetaVelvet_Ass_59 -ins_length 530 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A10/MetaVelvet_Ass_61 -ins_length 530 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A11/MetaVelvet_Ass_51 -ins_length 506 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A11/MetaVelvet_Ass_53 -ins_length 506 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A11/MetaVelvet_Ass_55 -ins_length 506 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A11/MetaVelvet_Ass_57 -ins_length 506 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A11/MetaVelvet_Ass_59 -ins_length 506 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A11/MetaVelvet_Ass_61 -ins_length 506 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A12/MetaVelvet_Ass_51 -ins_length 553 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A12/MetaVelvet_Ass_53 -ins_length 553 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A12/MetaVelvet_Ass_55 -ins_length 553 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A12/MetaVelvet_Ass_57 -ins_length 553 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A12/MetaVelvet_Ass_59 -ins_length 553 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A12/MetaVelvet_Ass_61 -ins_length 553 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H13/MetaVelvet_Ass_51 -ins_length 406 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H13/MetaVelvet_Ass_53 -ins_length 406 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H13/MetaVelvet_Ass_55 -ins_length 406 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H13/MetaVelvet_Ass_57 -ins_length 406 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H13/MetaVelvet_Ass_59 -ins_length 406 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H13/MetaVelvet_Ass_61 -ins_length 406 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H14/MetaVelvet_Ass_51 -ins_length 542 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H14/MetaVelvet_Ass_53 -ins_length 542 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H14/MetaVelvet_Ass_55 -ins_length 542 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H14/MetaVelvet_Ass_57 -ins_length 542 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H14/MetaVelvet_Ass_59 -ins_length 542 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H14/MetaVelvet_Ass_61 -ins_length 542 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H15/MetaVelvet_Ass_51 -ins_length 506 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H15/MetaVelvet_Ass_53 -ins_length 506 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H15/MetaVelvet_Ass_55 -ins_length 506 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H15/MetaVelvet_Ass_57 -ins_length 506 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H15/MetaVelvet_Ass_59 -ins_length 506 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H15/MetaVelvet_Ass_61 -ins_length 506 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A16/MetaVelvet_Ass_51 -ins_length 461 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A16/MetaVelvet_Ass_53 -ins_length 461 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A16/MetaVelvet_Ass_55 -ins_length 461 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A16/MetaVelvet_Ass_57 -ins_length 461 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A16/MetaVelvet_Ass_59 -ins_length 461 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A16/MetaVelvet_Ass_61 -ins_length 461 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A17/MetaVelvet_Ass_51 -ins_length 461 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A17/MetaVelvet_Ass_53 -ins_length 461 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A17/MetaVelvet_Ass_55 -ins_length 461 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A17/MetaVelvet_Ass_57 -ins_length 461 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A17/MetaVelvet_Ass_59 -ins_length 461 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A17/MetaVelvet_Ass_61 -ins_length 461 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A18/MetaVelvet_Ass_51 -ins_length 510 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A18/MetaVelvet_Ass_53 -ins_length 510 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A18/MetaVelvet_Ass_55 -ins_length 510 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A18/MetaVelvet_Ass_57 -ins_length 510 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A18/MetaVelvet_Ass_59 -ins_length 510 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A18/MetaVelvet_Ass_61 -ins_length 510 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A19/MetaVelvet_Ass_51 -ins_length 498 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A19/MetaVelvet_Ass_53 -ins_length 498 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A19/MetaVelvet_Ass_55 -ins_length 498 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A19/MetaVelvet_Ass_57 -ins_length 498 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A19/MetaVelvet_Ass_59 -ins_length 498 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A19/MetaVelvet_Ass_61 -ins_length 498 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A20/MetaVelvet_Ass_51 -ins_length 473 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A20/MetaVelvet_Ass_53 -ins_length 473 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A20/MetaVelvet_Ass_55 -ins_length 473 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A20/MetaVelvet_Ass_57 -ins_length 473 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A20/MetaVelvet_Ass_59 -ins_length 473 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A20/MetaVelvet_Ass_61 -ins_length 473 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A21/MetaVelvet_Ass_51 -ins_length 499 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A21/MetaVelvet_Ass_53 -ins_length 499 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A21/MetaVelvet_Ass_55 -ins_length 499 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A21/MetaVelvet_Ass_57 -ins_length 499 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A21/MetaVelvet_Ass_59 -ins_length 499 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A21/MetaVelvet_Ass_61 -ins_length 499 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A22/MetaVelvet_Ass_51 -ins_length 487 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A22/MetaVelvet_Ass_53 -ins_length 487 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A22/MetaVelvet_Ass_55 -ins_length 487 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A22/MetaVelvet_Ass_57 -ins_length 487 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A22/MetaVelvet_Ass_59 -ins_length 487 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A22/MetaVelvet_Ass_61 -ins_length 487 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A23/MetaVelvet_Ass_51 -ins_length 498 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A23/MetaVelvet_Ass_53 -ins_length 498 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A23/MetaVelvet_Ass_55 -ins_length 498 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A23/MetaVelvet_Ass_57 -ins_length 498 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A23/MetaVelvet_Ass_59 -ins_length 498 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A23/MetaVelvet_Ass_61 -ins_length 498 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A24/MetaVelvet_Ass_51 -ins_length 487 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A24/MetaVelvet_Ass_53 -ins_length 487 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A24/MetaVelvet_Ass_55 -ins_length 487 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A24/MetaVelvet_Ass_57 -ins_length 487 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A24/MetaVelvet_Ass_59 -ins_length 487 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A24/MetaVelvet_Ass_61 -ins_length 487 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A25/MetaVelvet_Ass_51 -ins_length 499 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A25/MetaVelvet_Ass_53 -ins_length 499 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A25/MetaVelvet_Ass_55 -ins_length 499 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A25/MetaVelvet_Ass_57 -ins_length 499 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A25/MetaVelvet_Ass_59 -ins_length 499 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A25/MetaVelvet_Ass_61 -ins_length 499 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A26/MetaVelvet_Ass_51 -ins_length 480 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A26/MetaVelvet_Ass_53 -ins_length 480 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A26/MetaVelvet_Ass_55 -ins_length 480 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A26/MetaVelvet_Ass_57 -ins_length 480 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A26/MetaVelvet_Ass_59 -ins_length 480 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A26/MetaVelvet_Ass_61 -ins_length 480 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A27/MetaVelvet_Ass_51 -ins_length 477 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A27/MetaVelvet_Ass_53 -ins_length 477 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A27/MetaVelvet_Ass_55 -ins_length 477 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A27/MetaVelvet_Ass_57 -ins_length 477 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A27/MetaVelvet_Ass_59 -ins_length 477 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A27/MetaVelvet_Ass_61 -ins_length 477 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A28/MetaVelvet_Ass_51 -ins_length 462 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A28/MetaVelvet_Ass_53 -ins_length 462 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A28/MetaVelvet_Ass_55 -ins_length 462 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A28/MetaVelvet_Ass_57 -ins_length 462 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A28/MetaVelvet_Ass_59 -ins_length 462 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A28/MetaVelvet_Ass_61 -ins_length 462 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A29/MetaVelvet_Ass_51 -ins_length 402 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A29/MetaVelvet_Ass_53 -ins_length 402 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A29/MetaVelvet_Ass_55 -ins_length 402 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A29/MetaVelvet_Ass_57 -ins_length 402 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A29/MetaVelvet_Ass_59 -ins_length 402 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A29/MetaVelvet_Ass_61 -ins_length 402 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A30/MetaVelvet_Ass_51 -ins_length 384 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A30/MetaVelvet_Ass_53 -ins_length 384 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A30/MetaVelvet_Ass_55 -ins_length 384 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A30/MetaVelvet_Ass_57 -ins_length 384 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A30/MetaVelvet_Ass_59 -ins_length 384 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A30/MetaVelvet_Ass_61 -ins_length 384 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A31/MetaVelvet_Ass_51 -ins_length 413 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A31/MetaVelvet_Ass_53 -ins_length 413 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A31/MetaVelvet_Ass_55 -ins_length 413 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A31/MetaVelvet_Ass_57 -ins_length 413 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A31/MetaVelvet_Ass_59 -ins_length 413 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A31/MetaVelvet_Ass_61 -ins_length 413 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A32/MetaVelvet_Ass_51 -ins_length 525 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A32/MetaVelvet_Ass_53 -ins_length 525 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A32/MetaVelvet_Ass_55 -ins_length 525 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A32/MetaVelvet_Ass_57 -ins_length 525 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A32/MetaVelvet_Ass_59 -ins_length 525 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A32/MetaVelvet_Ass_61 -ins_length 525 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A33/MetaVelvet_Ass_51 -ins_length 472 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A33/MetaVelvet_Ass_53 -ins_length 472 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A33/MetaVelvet_Ass_55 -ins_length 472 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A33/MetaVelvet_Ass_57 -ins_length 472 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A33/MetaVelvet_Ass_59 -ins_length 472 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A33/MetaVelvet_Ass_61 -ins_length 472 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A34/MetaVelvet_Ass_51 -ins_length 514 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A34/MetaVelvet_Ass_53 -ins_length 514 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A34/MetaVelvet_Ass_55 -ins_length 514 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A34/MetaVelvet_Ass_57 -ins_length 514 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A34/MetaVelvet_Ass_59 -ins_length 514 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A34/MetaVelvet_Ass_61 -ins_length 514 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A35/MetaVelvet_Ass_51 -ins_length 477 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A35/MetaVelvet_Ass_53 -ins_length 477 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A35/MetaVelvet_Ass_55 -ins_length 477 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A35/MetaVelvet_Ass_57 -ins_length 477 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A35/MetaVelvet_Ass_59 -ins_length 477 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A35/MetaVelvet_Ass_61 -ins_length 477 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H36/MetaVelvet_Ass_51 -ins_length 507 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H36/MetaVelvet_Ass_53 -ins_length 507 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H36/MetaVelvet_Ass_55 -ins_length 507 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H36/MetaVelvet_Ass_57 -ins_length 507 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H36/MetaVelvet_Ass_59 -ins_length 507 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H36/MetaVelvet_Ass_61 -ins_length 507 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H37/MetaVelvet_Ass_51 -ins_length 503 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H37/MetaVelvet_Ass_53 -ins_length 503 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H37/MetaVelvet_Ass_55 -ins_length 503 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H37/MetaVelvet_Ass_57 -ins_length 503 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H37/MetaVelvet_Ass_59 -ins_length 503 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H37/MetaVelvet_Ass_61 -ins_length 503 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H38/MetaVelvet_Ass_51 -ins_length 507 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H38/MetaVelvet_Ass_53 -ins_length 507 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H38/MetaVelvet_Ass_55 -ins_length 507 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H38/MetaVelvet_Ass_57 -ins_length 507 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H38/MetaVelvet_Ass_59 -ins_length 507 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H38/MetaVelvet_Ass_61 -ins_length 507 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H40/MetaVelvet_Ass_51 -ins_length 512 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H40/MetaVelvet_Ass_53 -ins_length 512 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H40/MetaVelvet_Ass_55 -ins_length 512 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H40/MetaVelvet_Ass_57 -ins_length 512 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H40/MetaVelvet_Ass_59 -ins_length 512 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H40/MetaVelvet_Ass_61 -ins_length 512 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H41/MetaVelvet_Ass_51 -ins_length 486 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H41/MetaVelvet_Ass_53 -ins_length 486 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H41/MetaVelvet_Ass_55 -ins_length 486 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H41/MetaVelvet_Ass_57 -ins_length 486 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H41/MetaVelvet_Ass_59 -ins_length 486 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H41/MetaVelvet_Ass_61 -ins_length 486 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H42/MetaVelvet_Ass_51 -ins_length 491 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H42/MetaVelvet_Ass_53 -ins_length 491 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H42/MetaVelvet_Ass_55 -ins_length 491 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H42/MetaVelvet_Ass_57 -ins_length 491 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H42/MetaVelvet_Ass_59 -ins_length 491 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H42/MetaVelvet_Ass_61 -ins_length 491 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H43/MetaVelvet_Ass_51 -ins_length 374 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H43/MetaVelvet_Ass_53 -ins_length 374 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H43/MetaVelvet_Ass_55 -ins_length 374 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H43/MetaVelvet_Ass_57 -ins_length 374 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H43/MetaVelvet_Ass_59 -ins_length 374 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H43/MetaVelvet_Ass_61 -ins_length 374 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H44/MetaVelvet_Ass_51 -ins_length 394 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H44/MetaVelvet_Ass_53 -ins_length 394 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H44/MetaVelvet_Ass_55 -ins_length 394 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H44/MetaVelvet_Ass_57 -ins_length 394 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H44/MetaVelvet_Ass_59 -ins_length 394 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H44/MetaVelvet_Ass_61 -ins_length 394 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H45/MetaVelvet_Ass_51 -ins_length 386 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H45/MetaVelvet_Ass_53 -ins_length 386 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H45/MetaVelvet_Ass_55 -ins_length 386 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H45/MetaVelvet_Ass_57 -ins_length 386 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H45/MetaVelvet_Ass_59 -ins_length 386 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H45/MetaVelvet_Ass_61 -ins_length 386 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H47/MetaVelvet_Ass_51 -ins_length 380 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H47/MetaVelvet_Ass_53 -ins_length 380 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H47/MetaVelvet_Ass_55 -ins_length 380 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H47/MetaVelvet_Ass_57 -ins_length 380 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H47/MetaVelvet_Ass_59 -ins_length 380 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H47/MetaVelvet_Ass_61 -ins_length 380 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H48/MetaVelvet_Ass_51 -ins_length 391 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H48/MetaVelvet_Ass_53 -ins_length 391 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H48/MetaVelvet_Ass_55 -ins_length 391 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H48/MetaVelvet_Ass_57 -ins_length 391 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H48/MetaVelvet_Ass_59 -ins_length 391 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H48/MetaVelvet_Ass_61 -ins_length 391 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H49/MetaVelvet_Ass_51 -ins_length 354 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H49/MetaVelvet_Ass_53 -ins_length 354 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H49/MetaVelvet_Ass_55 -ins_length 354 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H49/MetaVelvet_Ass_57 -ins_length 354 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H49/MetaVelvet_Ass_59 -ins_length 354 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H49/MetaVelvet_Ass_61 -ins_length 354 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H50/MetaVelvet_Ass_51 -ins_length 387 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H50/MetaVelvet_Ass_53 -ins_length 387 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H50/MetaVelvet_Ass_55 -ins_length 387 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H50/MetaVelvet_Ass_57 -ins_length 387 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H50/MetaVelvet_Ass_59 -ins_length 387 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H50/MetaVelvet_Ass_61 -ins_length 387 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H51/MetaVelvet_Ass_51 -ins_length 378 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H51/MetaVelvet_Ass_53 -ins_length 378 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H51/MetaVelvet_Ass_55 -ins_length 378 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H51/MetaVelvet_Ass_57 -ins_length 378 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H51/MetaVelvet_Ass_59 -ins_length 378 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H51/MetaVelvet_Ass_61 -ins_length 378 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H52/MetaVelvet_Ass_51 -ins_length 371 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H52/MetaVelvet_Ass_53 -ins_length 371 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H52/MetaVelvet_Ass_55 -ins_length 371 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H52/MetaVelvet_Ass_57 -ins_length 371 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H52/MetaVelvet_Ass_59 -ins_length 371 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H52/MetaVelvet_Ass_61 -ins_length 371 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H53/MetaVelvet_Ass_51 -ins_length 367 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H53/MetaVelvet_Ass_53 -ins_length 367 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H53/MetaVelvet_Ass_55 -ins_length 367 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H53/MetaVelvet_Ass_57 -ins_length 367 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H53/MetaVelvet_Ass_59 -ins_length 367 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/H53/MetaVelvet_Ass_61 -ins_length 367 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A5/MetaVelvet_Ass_51 -ins_length 518 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A5/MetaVelvet_Ass_53 -ins_length 518 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A5/MetaVelvet_Ass_55 -ins_length 518 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A5/MetaVelvet_Ass_57 -ins_length 518 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A5/MetaVelvet_Ass_59 -ins_length 518 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A5/MetaVelvet_Ass_61 -ins_length 518 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A8/MetaVelvet_Ass_51 -ins_length 518 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A8/MetaVelvet_Ass_53 -ins_length 518 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A8/MetaVelvet_Ass_55 -ins_length 518 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A8/MetaVelvet_Ass_57 -ins_length 518 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A8/MetaVelvet_Ass_59 -ins_length 518 -read_trkg yes
/data_center_01/soft/MetaVelvet/Velvet/velvet_1.2.10/velvetg /data_center_07/User/xujm/Oral_ZJU/analysis/01.Assemble/A8/MetaVelvet_Ass_61 -ins_length 518 -read_trkg yes
